#!/usr/bin/env python3
"""
Phase U26D2A
Balanced marker-based cell-type reconstruction for GSE252321.

Inputs
------
Four sparse cells-by-genes integer-count matrices generated by U26D1A v1.1.

Workflow
--------
1. Harmonize the common mouse gene universe across all four samples.
2. Retain adaptive-QC-passing cells.
3. Draw a balanced integration subset from every biological sample.
4. Library-size normalize and log1p transform.
5. Select highly variable genes without densifying the full matrix.
6. Run truncated SVD, sample-centroid correction and MiniBatchKMeans.
7. Annotate clusters with curated marker-panel scores.
8. Project all QC-passing cells onto the reconstruction.
9. Quantify sample-by-cell-type composition and targeted Treg/CD137L signals.
10. Produce annotation diagnostics for review before pseudobulk testing.

Biological samples remain the inferential units. This phase does not perform
cell-level significance testing and does not modify the manuscript or existing
Figures 1-6.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    from scipy import sparse
except ImportError as exc:
    raise SystemExit("ERROR: scipy is required.") from exc

try:
    from sklearn.cluster import MiniBatchKMeans
    from sklearn.decomposition import TruncatedSVD
except ImportError as exc:
    raise SystemExit(
        "ERROR: scikit-learn is required. Install with: "
        "python3 -m pip install --user scikit-learn"
    ) from exc

try:
    import matplotlib.pyplot as plt
except ImportError as exc:
    raise SystemExit("ERROR: matplotlib is required.") from exc


VERSION = "U26D2A_v1.0_2026-07-14"
TAG = "phaseU26D2A_GSE252321_marker_celltype_reconstruction"
SOURCE_TAG = "phaseU26D1A_GSE252321_flat_matrix_validation"
RANDOM_SEED = 26201


BROAD_MARKERS: Dict[str, List[str]] = {
    "urothelial_epithelial": [
        "UPK1A", "UPK1B", "UPK2", "UPK3A", "KRT8", "KRT18",
        "KRT19", "KRT20", "EPCAM", "KRT14", "KRT5",
    ],
    "macrophage_monocyte": [
        "ADGRE1", "LYZ2", "CSF1R", "FCGR1", "CTSS", "CD68",
        "C1QA", "C1QB", "C1QC", "TYROBP", "AIF1", "LST1",
    ],
    "dendritic": [
        "ITGAX", "H2-AA", "H2-AB1", "CD74", "FLT3", "XCR1",
        "CLEC10A", "CCR7", "FCER1A", "ZBTB46",
    ],
    "neutrophil": [
        "S100A8", "S100A9", "LY6G", "CSF3R", "MPO", "ELANE",
        "NGP", "RETNLG", "FCGR3", "CXCR2",
    ],
    "T_cell": [
        "CD3D", "CD3E", "CD3G", "TRAC", "LCK", "IL7R",
        "CD4", "CD8A", "CD8B1",
    ],
    "B_cell": [
        "CD79A", "CD79B", "MS4A1", "CD37", "CD74", "H2-AA",
        "CD19", "CD22", "CD83", "BANK1",
    ],
    "NK_cell": [
        "NKG7", "KLRD1", "NCR1", "PRF1", "GNLY", "GZMB",
        "GZMA", "CTSW", "TYROBP",
    ],
    "endothelial": [
        "PECAM1", "KDR", "EMCN", "CDH5", "VWF", "ENG",
        "ESAM", "RAMP2", "PLVAP",
    ],
    "fibroblast": [
        "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "PDGFRA",
        "COL6A1", "COL6A2", "COL6A3", "PI16",
    ],
    "smooth_muscle_pericyte": [
        "ACTA2", "TAGLN", "MYH11", "RGS5", "PDGFRB", "CSPG4",
        "MCAM", "DES", "NOTCH3",
    ],
    "mast_cell": [
        "KIT", "MCPT4", "MCPT1", "CPA3", "TPSB2", "HDC",
        "MS4A2", "GATA2",
    ],
}

TARGETED_MARKERS: Dict[str, List[str]] = {
    "Treg": ["FOXP3", "IL2RA", "CTLA4", "IKZF2", "TNFRSF18"],
    "CD137L_macrophage": ["TNFSF9", "ADGRE1", "LYZ2", "CSF1R", "CD68"],
    "cycling": ["MKI67", "TOP2A", "CENPF", "UBE2C", "TYMS"],
    "interferon_response": ["ISG15", "IFIT1", "IFIT3", "MX1", "OAS1A"],
}


def log(message: str) -> None:
    print(f"[U26D2A] {message}", flush=True)


def read_tsv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, sep="\t", compression="infer", low_memory=False)


def normalize_gene(value: object) -> str:
    return str(value).strip().upper()


def load_manifest(project: Path) -> pd.DataFrame:
    path = (
        project / "03_metadata" / SOURCE_TAG
        / "UTI_HostOmics_U26D1A_sparse_matrix_manifest.tsv"
    )
    if not path.exists():
        raise FileNotFoundError(f"U26D1A manifest not found: {path}")
    manifest = read_tsv(path)
    required = {
        "sample_id", "condition", "sparse_matrix_path", "genes_path",
        "cell_metadata_path",
    }
    missing = sorted(required - set(manifest.columns))
    if missing:
        raise RuntimeError(f"Manifest missing columns: {missing}")
    if len(manifest) != 4:
        raise RuntimeError(f"Expected four samples, found {len(manifest)}")
    return manifest


def load_gene_map(path: Path) -> Tuple[List[str], Dict[str, int]]:
    genes = read_tsv(path)
    if "gene_symbol" not in genes.columns:
        raise RuntimeError(f"gene_symbol missing from {path}")
    symbols = genes["gene_symbol"].map(normalize_gene).tolist()
    mapping: Dict[str, int] = {}
    for index, symbol in enumerate(symbols):
        if symbol and symbol not in mapping:
            mapping[symbol] = index
    return symbols, mapping


def common_gene_universe(
    manifest: pd.DataFrame,
) -> Tuple[List[str], Dict[str, Dict[str, int]], pd.DataFrame]:
    sample_maps: Dict[str, Dict[str, int]] = {}
    audit_rows = []
    intersection: set[str] | None = None

    for _, row in manifest.iterrows():
        sample_id = str(row["sample_id"])
        symbols, mapping = load_gene_map(Path(str(row["genes_path"])))
        sample_maps[sample_id] = mapping
        gene_set = set(mapping)
        intersection = gene_set if intersection is None else intersection & gene_set
        audit_rows.append(
            {
                "sample_id": sample_id,
                "n_gene_rows": len(symbols),
                "n_unique_uppercase_genes": len(mapping),
                "n_duplicate_after_uppercase": len(symbols) - len(mapping),
            }
        )

    common = sorted(intersection or set())
    if len(common) < 8000:
        raise RuntimeError(
            f"Only {len(common)} genes are common to all samples."
        )

    for row in audit_rows:
        row["n_common_genes"] = len(common)
        row["common_gene_fraction"] = (
            len(common) / row["n_unique_uppercase_genes"]
        )

    return common, sample_maps, pd.DataFrame(audit_rows)


def load_sample(
    row: pd.Series,
    common_genes: Sequence[str],
    mapping: Dict[str, int],
) -> Tuple[sparse.csr_matrix, pd.DataFrame]:
    matrix = sparse.load_npz(
        Path(str(row["sparse_matrix_path"]))
    ).tocsr()
    cells = read_tsv(Path(str(row["cell_metadata_path"])))

    if matrix.shape[0] != len(cells):
        raise RuntimeError(
            f"Cell metadata mismatch for {row['sample_id']}: "
            f"matrix={matrix.shape[0]}, metadata={len(cells)}"
        )

    indices = np.asarray([mapping[gene] for gene in common_genes], dtype=int)
    matrix = matrix[:, indices].tocsr()

    qc_mask = (
        cells["adaptive_qc_pass"]
        .astype(str)
        .str.lower()
        .isin(["true", "1"])
        .to_numpy()
    )
    matrix = matrix[qc_mask].tocsr()
    cells = cells.loc[qc_mask].reset_index(drop=True)

    if matrix.shape[0] < 500:
        raise RuntimeError(
            f"Too few QC-passing cells for {row['sample_id']}: "
            f"{matrix.shape[0]}"
        )

    return matrix, cells


def normalize_log1p(
    matrix: sparse.csr_matrix,
    target_sum: float = 10000.0,
) -> sparse.csr_matrix:
    matrix = matrix.astype(np.float32, copy=True)
    totals = np.asarray(matrix.sum(axis=1)).ravel()
    factors = np.divide(
        target_sum,
        totals,
        out=np.zeros_like(totals, dtype=np.float32),
        where=totals > 0,
    )
    matrix = sparse.diags(factors).dot(matrix).tocsr()
    matrix.data = np.log1p(matrix.data)
    return matrix


def select_hvgs(
    matrix: sparse.csr_matrix,
    genes: Sequence[str],
    n_hvg: int,
) -> Tuple[np.ndarray, pd.DataFrame]:
    means = np.asarray(matrix.mean(axis=0)).ravel()
    means_sq = np.asarray(matrix.power(2).mean(axis=0)).ravel()
    variances = np.maximum(means_sq - means**2, 0.0)
    dispersions = variances / (means + 1e-6)

    exclude = np.asarray(
        [
            gene.startswith("MT-")
            or gene.startswith("RPL")
            or gene.startswith("RPS")
            or gene in {"MALAT1", "XIST"}
            for gene in genes
        ],
        dtype=bool,
    )
    eligible = (~exclude) & np.isfinite(dispersions) & (means > 0.01)
    eligible_indices = np.where(eligible)[0]
    if len(eligible_indices) < 500:
        raise RuntimeError("Too few eligible genes for variable-gene selection.")

    order = eligible_indices[
        np.argsort(dispersions[eligible_indices])[::-1]
    ]
    selected = order[: min(n_hvg, len(order))]

    table = pd.DataFrame(
        {
            "gene_symbol": np.asarray(genes)[selected],
            "mean_log_expression": means[selected],
            "variance_log_expression": variances[selected],
            "dispersion_score": dispersions[selected],
            "hvg_rank": np.arange(1, len(selected) + 1),
        }
    )
    return selected, table


def panel_indices(
    genes: Sequence[str],
    panels: Dict[str, List[str]],
) -> Tuple[Dict[str, np.ndarray], pd.DataFrame]:
    lookup = {gene: index for index, gene in enumerate(genes)}
    output: Dict[str, np.ndarray] = {}
    audit_rows = []

    for panel, markers in panels.items():
        detected = [marker for marker in markers if marker in lookup]
        output[panel] = np.asarray(
            [lookup[marker] for marker in detected],
            dtype=int,
        )
        audit_rows.append(
            {
                "panel": panel,
                "n_markers_requested": len(markers),
                "n_markers_detected": len(detected),
                "coverage_fraction": len(detected) / len(markers),
                "detected_markers": ";".join(detected),
                "missing_markers": ";".join(
                    [marker for marker in markers if marker not in lookup]
                ),
            }
        )
    return output, pd.DataFrame(audit_rows)


def marker_scores(
    log_matrix: sparse.csr_matrix,
    indices: Dict[str, np.ndarray],
) -> pd.DataFrame:
    scores = {}
    for panel, panel_indices_ in indices.items():
        if len(panel_indices_) == 0:
            scores[panel] = np.zeros(log_matrix.shape[0])
        else:
            scores[panel] = np.asarray(
                log_matrix[:, panel_indices_].mean(axis=1)
            ).ravel()
    return pd.DataFrame(scores)


def zscore_columns(frame: pd.DataFrame) -> pd.DataFrame:
    means = frame.mean(axis=0)
    standard = frame.std(axis=0, ddof=1).replace(0, 1.0)
    return (frame - means) / standard


def annotate_clusters(
    clusters: np.ndarray,
    broad_scores: pd.DataFrame,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    standardized = zscore_columns(broad_scores)
    standardized["cluster"] = clusters
    cluster_means = standardized.groupby("cluster").mean()

    rows = []
    for cluster, values in cluster_means.iterrows():
        ordered = values.sort_values(ascending=False)
        best_label = str(ordered.index[0])
        best_score = float(ordered.iloc[0])
        second_score = float(ordered.iloc[1]) if len(ordered) > 1 else np.nan
        margin = best_score - second_score if np.isfinite(second_score) else np.nan

        if best_score < -0.10 or (np.isfinite(margin) and margin < 0.12):
            final_label = "mixed_low_confidence"
            confidence = "low"
        elif margin < 0.35:
            final_label = best_label
            confidence = "moderate"
        else:
            final_label = best_label
            confidence = "high"

        rows.append(
            {
                "cluster": int(cluster),
                "broad_cell_type": final_label,
                "annotation_confidence": confidence,
                "top_marker_panel": best_label,
                "top_panel_zscore": best_score,
                "second_panel_zscore": second_score,
                "top_minus_second_margin": margin,
                "cluster_cells_in_balanced_subset": int(
                    np.sum(clusters == cluster)
                ),
            }
        )

    annotation = pd.DataFrame(rows).sort_values("cluster")
    cluster_panel_scores = cluster_means.reset_index()
    return annotation, cluster_panel_scores


def top_cluster_markers(
    log_hvg: sparse.csr_matrix,
    clusters: np.ndarray,
    hvg_genes: Sequence[str],
    top_n: int = 25,
) -> pd.DataFrame:
    global_mean = np.asarray(log_hvg.mean(axis=0)).ravel()
    rows = []

    for cluster in sorted(np.unique(clusters)):
        mask = clusters == cluster
        cluster_mean = np.asarray(
            log_hvg[mask].mean(axis=0)
        ).ravel()
        outside_mean = np.asarray(
            log_hvg[~mask].mean(axis=0)
        ).ravel()
        specificity = cluster_mean - outside_mean
        order = np.argsort(specificity)[::-1][:top_n]
        for rank, index in enumerate(order, start=1):
            rows.append(
                {
                    "cluster": int(cluster),
                    "rank": rank,
                    "gene_symbol": hvg_genes[index],
                    "cluster_mean_log_expression": cluster_mean[index],
                    "outside_mean_log_expression": outside_mean[index],
                    "specificity_difference": specificity[index],
                    "global_mean_log_expression": global_mean[index],
                }
            )
    return pd.DataFrame(rows)


def save_scatter(
    coordinates: np.ndarray,
    labels: Sequence[object],
    output_path: Path,
    title: str,
) -> None:
    figure = plt.figure(figsize=(9, 7))
    axis = figure.add_axes([0.12, 0.12, 0.70, 0.78])
    unique = pd.Series(labels).astype(str).unique()

    for label in unique:
        mask = np.asarray(pd.Series(labels).astype(str) == label)
        axis.scatter(
            coordinates[mask, 0],
            coordinates[mask, 1],
            s=5,
            alpha=0.55,
            label=label,
        )

    axis.set_xlabel("Corrected component 1")
    axis.set_ylabel("Corrected component 2")
    axis.set_title(title)
    axis.legend(
        loc="upper left",
        bbox_to_anchor=(1.02, 1.0),
        fontsize=7,
        markerscale=2,
    )
    figure.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def save_composition_plot(
    composition: pd.DataFrame,
    output_path: Path,
) -> None:
    pivot = composition.pivot(
        index="sample_id",
        columns="broad_cell_type",
        values="fraction_of_QC_cells",
    ).fillna(0.0)

    figure = plt.figure(figsize=(11, 6))
    axis = figure.add_axes([0.10, 0.24, 0.72, 0.66])
    pivot.plot(kind="bar", stacked=True, ax=axis)
    axis.set_ylabel("Fraction of QC-passing cells")
    axis.set_xlabel("Biological sample")
    axis.set_title("GSE252321 reconstructed cell-type composition")
    axis.legend(
        loc="upper left",
        bbox_to_anchor=(1.02, 1.0),
        fontsize=7,
    )
    figure.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--project-root",
        default="__UTI_HOSTOMICS_PROJECT_ROOT__",
    )
    parser.add_argument("--balanced-cells-per-sample", type=int, default=2500)
    parser.add_argument("--n-hvg", type=int, default=2500)
    parser.add_argument("--n-components", type=int, default=30)
    parser.add_argument("--n-clusters", type=int, default=18)
    args = parser.parse_args()

    project = Path(args.project_root).resolve()
    rng = np.random.default_rng(RANDOM_SEED)

    out_processed = project / "03_data_processed" / TAG
    out_metadata = project / "03_metadata" / TAG
    out_tables = project / "06_tables" / TAG
    out_results = project / "05_results" / TAG
    out_figures = project / "06_figures" / TAG

    for directory in [
        out_processed, out_metadata, out_tables, out_results, out_figures
    ]:
        directory.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest(project)
    common_genes, sample_maps, gene_audit = common_gene_universe(manifest)
    gene_audit.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_common_gene_audit.tsv",
        sep="\t",
        index=False,
    )

    all_panels = {**BROAD_MARKERS, **TARGETED_MARKERS}
    all_panel_indices, marker_audit = panel_indices(common_genes, all_panels)
    broad_panel_indices = {
        panel: all_panel_indices[panel] for panel in BROAD_MARKERS
    }
    targeted_panel_indices = {
        panel: all_panel_indices[panel] for panel in TARGETED_MARKERS
    }
    marker_audit.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_marker_panel_coverage.tsv",
        sep="\t",
        index=False,
    )

    balanced_matrices = []
    balanced_metadata = []
    loaded_samples: Dict[str, Tuple[sparse.csr_matrix, pd.DataFrame]] = {}

    for _, row in manifest.iterrows():
        sample_id = str(row["sample_id"])
        log(f"Loading QC-passing cells for {sample_id}.")
        matrix, cells = load_sample(
            row,
            common_genes,
            sample_maps[sample_id],
        )
        loaded_samples[sample_id] = (matrix, cells)

        n_select = min(args.balanced_cells_per_sample, matrix.shape[0])
        selected = np.sort(
            rng.choice(matrix.shape[0], size=n_select, replace=False)
        )
        normalized = normalize_log1p(matrix[selected])
        balanced_matrices.append(normalized)

        selected_cells = cells.iloc[selected].copy()
        selected_cells["balanced_subset_row"] = np.arange(n_select)
        balanced_metadata.append(selected_cells)

    balanced_matrix = sparse.vstack(
        balanced_matrices,
        format="csr",
    )
    balanced_cells = pd.concat(
        balanced_metadata,
        ignore_index=True,
    )

    log(
        f"Balanced integration matrix: {balanced_matrix.shape[0]} cells x "
        f"{balanced_matrix.shape[1]} common genes."
    )

    hvg_indices, hvg_table = select_hvgs(
        balanced_matrix,
        common_genes,
        args.n_hvg,
    )
    hvg_table.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_highly_variable_genes.tsv",
        sep="\t",
        index=False,
    )
    hvg_genes = [common_genes[index] for index in hvg_indices]
    balanced_hvg = balanced_matrix[:, hvg_indices].tocsr()

    n_components = min(
        args.n_components,
        balanced_hvg.shape[0] - 1,
        balanced_hvg.shape[1] - 1,
    )
    log(f"Running TruncatedSVD with {n_components} components.")
    svd = TruncatedSVD(
        n_components=n_components,
        random_state=RANDOM_SEED,
        n_iter=7,
    )
    coordinates = svd.fit_transform(balanced_hvg)

    sample_centers: Dict[str, np.ndarray] = {}
    corrected = coordinates.copy()
    for sample_id in balanced_cells["sample_id"].astype(str).unique():
        mask = (
            balanced_cells["sample_id"].astype(str).to_numpy()
            == sample_id
        )
        center = coordinates[mask].mean(axis=0)
        sample_centers[sample_id] = center
        corrected[mask] -= center

    component_scale = corrected.std(axis=0, ddof=1)
    component_scale[component_scale == 0] = 1.0
    corrected /= component_scale

    log(f"Clustering balanced cells into {args.n_clusters} clusters.")
    clusterer = MiniBatchKMeans(
        n_clusters=args.n_clusters,
        random_state=RANDOM_SEED,
        batch_size=1024,
        n_init=20,
        max_iter=300,
    )
    balanced_clusters = clusterer.fit_predict(corrected)

    broad_scores_balanced = marker_scores(
        balanced_matrix,
        broad_panel_indices,
    )
    cluster_annotation, cluster_panel_scores = annotate_clusters(
        balanced_clusters,
        broad_scores_balanced,
    )
    cluster_annotation.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_cluster_annotations.tsv",
        sep="\t",
        index=False,
    )
    cluster_panel_scores.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_cluster_marker_panel_scores.tsv",
        sep="\t",
        index=False,
    )

    cluster_lookup = (
        cluster_annotation.set_index("cluster")["broad_cell_type"].to_dict()
    )
    confidence_lookup = (
        cluster_annotation.set_index("cluster")[
            "annotation_confidence"
        ].to_dict()
    )

    marker_table = top_cluster_markers(
        balanced_hvg,
        balanced_clusters,
        hvg_genes,
    )
    marker_table.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_cluster_top_markers.tsv",
        sep="\t",
        index=False,
    )

    balanced_cells["cluster"] = balanced_clusters
    balanced_cells["broad_cell_type"] = [
        cluster_lookup[int(cluster)] for cluster in balanced_clusters
    ]
    balanced_cells["annotation_confidence"] = [
        confidence_lookup[int(cluster)] for cluster in balanced_clusters
    ]
    balanced_cells["corrected_component_1"] = corrected[:, 0]
    balanced_cells["corrected_component_2"] = corrected[:, 1]
    balanced_cells.to_csv(
        out_metadata / "UTI_HostOmics_U26D2A_balanced_cell_annotations.tsv.gz",
        sep="\t",
        index=False,
        compression="gzip",
    )

    save_scatter(
        corrected,
        balanced_clusters,
        out_figures / "UTI_HostOmics_U26D2A_balanced_clusters.png",
        "GSE252321 balanced reconstruction by cluster",
    )
    save_scatter(
        corrected,
        balanced_cells["broad_cell_type"],
        out_figures / "UTI_HostOmics_U26D2A_balanced_celltypes.png",
        "GSE252321 marker-based broad cell types",
    )

    all_annotations = []
    sample_cluster_rows = []
    sample_type_rows = []
    targeted_rows = []

    for _, row in manifest.iterrows():
        sample_id = str(row["sample_id"])
        condition = str(row["condition"])
        matrix, cells = loaded_samples[sample_id]
        log(f"Projecting all {len(cells)} QC cells from {sample_id}.")

        normalized = normalize_log1p(matrix)
        sample_coordinates = svd.transform(
            normalized[:, hvg_indices]
        )
        sample_corrected = (
            sample_coordinates - sample_centers[sample_id]
        ) / component_scale
        clusters = clusterer.predict(sample_corrected)
        broad_types = np.asarray(
            [cluster_lookup[int(cluster)] for cluster in clusters],
            dtype=object,
        )
        confidences = np.asarray(
            [confidence_lookup[int(cluster)] for cluster in clusters],
            dtype=object,
        )

        targeted_scores = marker_scores(
            normalized,
            targeted_panel_indices,
        )
        broad_scores = marker_scores(
            normalized,
            broad_panel_indices,
        )

        annotation = cells.copy()
        annotation["cluster"] = clusters
        annotation["broad_cell_type"] = broad_types
        annotation["annotation_confidence"] = confidences
        annotation["corrected_component_1"] = sample_corrected[:, 0]
        annotation["corrected_component_2"] = sample_corrected[:, 1]

        for column in targeted_scores.columns:
            annotation[f"{column}_score"] = targeted_scores[column].to_numpy()

        t_cell_mask = broad_types == "T_cell"
        if t_cell_mask.any():
            treg_threshold = float(
                np.quantile(
                    targeted_scores.loc[t_cell_mask, "Treg"],
                    0.80,
                )
            )
        else:
            treg_threshold = np.inf
        annotation["Treg_candidate"] = (
            t_cell_mask
            & (
                targeted_scores["Treg"].to_numpy()
                >= treg_threshold
            )
            & (targeted_scores["Treg"].to_numpy() > 0)
        )

        macrophage_mask = broad_types == "macrophage_monocyte"
        if macrophage_mask.any():
            cd137_threshold = float(
                np.quantile(
                    targeted_scores.loc[
                        macrophage_mask,
                        "CD137L_macrophage",
                    ],
                    0.80,
                )
            )
        else:
            cd137_threshold = np.inf
        annotation["CD137L_high_macrophage_candidate"] = (
            macrophage_mask
            & (
                targeted_scores["CD137L_macrophage"].to_numpy()
                >= cd137_threshold
            )
            & (
                targeted_scores[
                    "CD137L_macrophage"
                ].to_numpy()
                > 0
            )
        )

        all_annotations.append(annotation)

        for cluster, count in pd.Series(clusters).value_counts().items():
            sample_cluster_rows.append(
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "cluster": int(cluster),
                    "n_cells": int(count),
                    "fraction_of_QC_cells": count / len(annotation),
                }
            )

        for cell_type, count in pd.Series(broad_types).value_counts().items():
            sample_type_rows.append(
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "broad_cell_type": str(cell_type),
                    "n_cells": int(count),
                    "fraction_of_QC_cells": count / len(annotation),
                }
            )

        targeted_rows.extend(
            [
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "targeted_population": "Treg_candidate",
                    "parent_population": "T_cell",
                    "parent_cells": int(t_cell_mask.sum()),
                    "candidate_cells": int(
                        annotation["Treg_candidate"].sum()
                    ),
                    "candidate_fraction_within_parent": (
                        float(annotation.loc[t_cell_mask, "Treg_candidate"].mean())
                        if t_cell_mask.any()
                        else np.nan
                    ),
                },
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "targeted_population": (
                        "CD137L_high_macrophage_candidate"
                    ),
                    "parent_population": "macrophage_monocyte",
                    "parent_cells": int(macrophage_mask.sum()),
                    "candidate_cells": int(
                        annotation[
                            "CD137L_high_macrophage_candidate"
                        ].sum()
                    ),
                    "candidate_fraction_within_parent": (
                        float(
                            annotation.loc[
                                macrophage_mask,
                                "CD137L_high_macrophage_candidate",
                            ].mean()
                        )
                        if macrophage_mask.any()
                        else np.nan
                    ),
                },
            ]
        )

    all_cell_annotations = pd.concat(all_annotations, ignore_index=True)
    all_cell_annotations.to_csv(
        out_metadata / "UTI_HostOmics_U26D2A_all_QC_cell_annotations.tsv.gz",
        sep="\t",
        index=False,
        compression="gzip",
    )

    sample_clusters = pd.DataFrame(sample_cluster_rows)
    sample_clusters.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_sample_cluster_composition.tsv",
        sep="\t",
        index=False,
    )

    sample_types = pd.DataFrame(sample_type_rows)
    sample_types.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_sample_celltype_composition.tsv",
        sep="\t",
        index=False,
    )

    targeted = pd.DataFrame(targeted_rows)
    targeted.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_targeted_population_summary.tsv",
        sep="\t",
        index=False,
    )

    save_composition_plot(
        sample_types,
        out_figures / "UTI_HostOmics_U26D2A_celltype_composition.png",
    )

    type_sample_presence = (
        sample_types.assign(present=sample_types["n_cells"] >= 30)
        .pivot_table(
            index="broad_cell_type",
            columns="sample_id",
            values="present",
            aggfunc="max",
            fill_value=False,
        )
    )
    type_sample_presence.to_csv(
        out_tables / "UTI_HostOmics_U26D2A_celltype_sample_presence.tsv",
        sep="\t",
    )

    confident_fraction = float(
        (
            all_cell_annotations["annotation_confidence"]
            .astype(str)
            .isin(["high", "moderate"])
        ).mean()
    )
    n_cell_types = int(
        all_cell_annotations["broad_cell_type"].nunique()
    )
    types_all_samples = int(
        (type_sample_presence.sum(axis=1) == 4).sum()
    )
    macrophage_present = bool(
        "macrophage_monocyte" in type_sample_presence.index
        and type_sample_presence.loc[
            "macrophage_monocyte"
        ].sum() >= 3
    )
    tcell_present = bool(
        "T_cell" in type_sample_presence.index
        and type_sample_presence.loc["T_cell"].sum() >= 3
    )

    if (
        n_cell_types >= 5
        and confident_fraction >= 0.65
        and types_all_samples >= 3
        and macrophage_present
        and tcell_present
    ):
        decision = "READY_FOR_U26D2B_CELLTYPE_PSEUDOBULK_SCORING"
    else:
        decision = "TARGETED_CELLTYPE_ANNOTATION_REVIEW_REQUIRED"

    pd.DataFrame(
        [
            {
                "phase": "U26D2A",
                "decision": decision,
                "n_QC_cells_annotated": len(all_cell_annotations),
                "n_common_genes": len(common_genes),
                "balanced_integration_cells": len(balanced_cells),
                "n_HVGs": len(hvg_indices),
                "n_clusters": args.n_clusters,
                "n_broad_cell_types": n_cell_types,
                "moderate_or_high_confidence_fraction": confident_fraction,
                "n_cell_types_with_at_least_30_cells_in_all_four_samples": (
                    types_all_samples
                ),
                "macrophage_present_in_at_least_three_samples": (
                    macrophage_present
                ),
                "T_cell_present_in_at_least_three_samples": tcell_present,
                "biological_sample_is_inferential_unit": True,
                "cell_level_significance_testing_performed": False,
                "manuscript_modified": False,
                "existing_figures_modified": False,
                "next_phase": (
                    "U26D2B sample-by-cell-type pseudobulk module scoring"
                    if decision
                    == "READY_FOR_U26D2B_CELLTYPE_PSEUDOBULK_SCORING"
                    else "Review cluster markers and annotation confidence"
                ),
            }
        ]
    ).to_csv(
        out_tables / "UTI_HostOmics_U26D2A_phase_decision.tsv",
        sep="\t",
        index=False,
    )

    report_path = (
        out_results
        / "UTI_HostOmics_U26D2A_celltype_reconstruction_report.md"
    )
    with report_path.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Phase U26D2A - GSE252321 marker-based cell-type reconstruction\n\n"
        )
        handle.write(f"- Version: `{VERSION}`\n")
        handle.write(f"- Decision: **{decision}**\n")
        handle.write(
            f"- QC-passing cells annotated: **{len(all_cell_annotations):,}**.\n"
        )
        handle.write(f"- Common genes: **{len(common_genes):,}**.\n")
        handle.write(
            f"- Balanced integration cells: **{len(balanced_cells):,}**.\n"
        )
        handle.write(f"- Broad cell types: **{n_cell_types}**.\n")
        handle.write(
            f"- Moderate/high annotation confidence: "
            f"**{confident_fraction:.1%}**.\n"
        )
        handle.write(
            f"- Cell types represented by at least 30 cells in all four "
            f"samples: **{types_all_samples}**.\n\n"
        )
        handle.write("## Statistical boundary\n\n")
        handle.write(
            "Clusters and cell-level marker scores are used for annotation and "
            "descriptive composition only. UPEC-versus-control inference will "
            "use sample-by-cell-type pseudobulk values, with the four biological "
            "samples as the units of analysis.\n\n"
        )
        handle.write("## Targeted populations\n\n")
        for _, item in targeted.iterrows():
            handle.write(
                f"- `{item['sample_id']}` {item['targeted_population']}: "
                f"{int(item['candidate_cells'])}/{int(item['parent_cells'])} "
                f"parent cells.\n"
            )

    manifest_out = {
        "version": VERSION,
        "decision": decision,
        "n_QC_cells_annotated": int(len(all_cell_annotations)),
        "n_common_genes": int(len(common_genes)),
        "n_broad_cell_types": n_cell_types,
        "manuscript_modified": False,
        "existing_figures_modified": False,
    }
    (
        out_results / "UTI_HostOmics_U26D2A_run_manifest.json"
    ).write_text(json.dumps(manifest_out, indent=2), encoding="utf-8")

    log(f"QC cells annotated: {len(all_cell_annotations):,}")
    log(f"Common genes: {len(common_genes):,}")
    log(f"Broad cell types: {n_cell_types}")
    log(
        f"Moderate/high confidence fraction: "
        f"{confident_fraction:.1%}"
    )
    log(f"Decision: {decision}")
    log(f"Report: {report_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[U26D2A] ERROR: {exc}", file=sys.stderr)
        raise
